name: generate-changelog

on:
  push:
    branches:
      - release/[0-9]+.[0-9]+.[0-9]+

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: gradle/gradle-build-action@v2.2.5
        with:
          arguments: changelog

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(release): update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
